FormSite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf.urls.static import static
from django.conf import settings
from .views import about, homepage

from articles.views import article_list


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^about/$', about),
    url(r'^$', article_list, name="home"),
    
]


urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url

from .views import signup_view, login_view, logout_view


app_name = 'accounts'




urlpatterns = [
	url(r'^signup/$', signup_view, name="signup"),
	url(r'^login/$', login_view, name="login"),
	url(r'^logout/$', logout_view, name="logout"),
]

articles/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url

from .views import article_list, article_detail, article_create


app_name = 'articles'

urlpatterns = [  
	url(r'^$', article_list, name="list"), 
	url(r'^create/$', article_create, name="create"),
	url(r'^(?P<slug>[\w-]+)/$', article_detail, name="detail"),
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
 

class Article(models.Model):
	title = models.CharField(max_length=100)
	slug = models.SlugField()
	body = models.TextField()
	date = models.DateTimeField(auto_now_add=True) #this
			#will automatically populate this field with time now
	
	thumb = models.ImageField(default='default.png', blank=True)
	author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)


	def __str__(self):
		return self.title



	def snippet(self):
		string = self.body[:50] 
		if(len(string) == 50):
			string = string + " ..."

		return string

articles/forms.py
#all model forms for articles will be in this file

from django import forms
from . import models




class CreateArticle(forms.ModelForm):
	class Meta:
		model = models.Article
		fields = ['title', 'body', 'slug', 'thumb']
		

FormSite/views.py
from django.http import HttpResponse

from django.shortcuts import render


def about(request): 
	return render(request, "about.html")	


def homepage(request): 
	return render(request, "homepage.html")
	

accounts/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.contrib.auth import login, logout


#this function is fired in both get and post request
def signup_view(request):

	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save() #this function automatically returns the user
			login(request, user)

			return redirect("articles:list")



	else:
		form = UserCreationForm()
		 

	return render(request, 'accounts/signup.html', {'form':form})





def login_view(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			#log in the user
			user = form.get_user() #this is gonna retrieve the user that is trying to login
			login(request, user)

			if "next" in request.POST:
				return redirect(request.POST.get('next'))
			else:
				return redirect("articles:list")

	else:
		form = AuthenticationForm()

	return render(request, "accounts/login.html", {'form':form})





def logout_view(request):
	if request.method == 'POST':
		logout(request)

		return redirect("articles:list")

articles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Article
from .forms import CreateArticle
#decorator
from django.contrib.auth.decorators import login_required


def article_list(request):
	articles = Article.objects.all().order_by("date")

	return render(request, 'articles/article_list.html', {'articles' : articles})




def article_detail(request, slug):
	article = Article.objects.get(slug=slug)

	return render(request, 'articles/article_detail.html', {'article':article})



#this decorator is protecting the article_create view function
#so if user is logged in, then only this function will fire
@login_required(login_url="/accounts/login/")
def article_create(request):

	if request.method == 'POST':
		form = CreateArticle(request.POST, request.FILES)
		#request.FILES is done coz we are uploading an image i.e. file, so a separate
		#request.FILES must be done

		if form.is_valid():
			#save this article to db
			instance = form.save(commit=False)
			instance.author = request.user
			instance.save()
			
			return redirect("articles:list")

	else:
		form = CreateArticle()

	return render(request, "articles/article_create.html", {'form':form})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}




{% block content %}
	<h1>Login</h1>
	<form class="site-form" action="{% url 'accounts:login' %}" method="post">
		{% csrf_token %}
		{{form}}
		{% if request.GET.next %}
			<input type="hidden" name="next" value="{{request.GET.next}}">
		{% endif %}

		<input type="submit" value="Log In">
	</form>
		 

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}
 

{% block content %}
	<form class="site-form" action="/accounts/signup/" method="post">
		{% csrf_token %}
		
		{{form}}
		<input type="submit" name="" value="Signup">
	</form>

{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}



{% block content %}
	
	<div class="create-article">
	<h2>Create An Article</h2>

		<form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
			{{form}}
		 
		<input type="submit" value="Create">
		</form>

	</div>
	<script src="/static/slugify.js"></script>

{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}
 
{% block content %}

<div class="article-detail">
	<div class="article">

	<img src="{{ article.thumb.url }}">
	
	<h2>{{ article.title }}</h2>
	<p>{{ article.body }}</p>
	<p>{{ article.date }}</p>

	</div>


</div>


{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %} 

{% block content %}

	<h1>The Articles to show are following</h1>
	<div class="articles">
		{% for article in articles %}
			<div class="article">
				<div class="article-title"><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></div>

				<div class="author"><small>Author: {{article.author }}</small></div>

				<p>{{ article.snippet }}</p>
				<p>{{ article.date }}</p>
			</div> 
		{% endfor %}
	</div>
 


{% endblock %}

templates/about.html
<!DOCTYPE html>
<html>
<head>
	<title>About</title>
</head>
<body>
	<h1>About Page</h1>
</body>
</html>

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Blog Site</title>
	<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
	<header class="wrapper">
	<div class="image-logo"><a href="{% url 'home' %}"><img src="{% static 'logo2.jpg' %}"></a></div>

	<nav>
		<ul>
			{% if user.is_authenticated %}
			<li>
				<form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
					{% csrf_token %}
					<button type="submit">Logout</button>
				</form>
			</li>
			
			<li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>

			{% else %}
				<li><a href="{% url 'accounts:login' %}">Login</a></li>
				<li><a href="{% url 'accounts:signup' %}">SignUp</a></li>

			{% endif %}
		</ul>
	</nav>	
	
	</header>

	

	<!--
	<div class="sk-folding-cube">
	  <div class="sk-cube1 sk-cube"></div>
	  <div class="sk-cube2 sk-cube"></div>
	  <div class="sk-cube4 sk-cube"></div>
	  <div class="sk-cube3 sk-cube"></div>
	</div>
	-->











	<div class="wrapper">
		{% block content %}
		{% endblock %}
	</div>

</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
<head>
	<title>HomePage</title>
</head>
<body>
	<h1>This is the homepage</h1>

</body>
</html>